import {
  Banknote,
  BarChart3,
  Bell,
  Boxes,
  Briefcase,
  FileSpreadsheet,
  Building2,
  CircleUserRound,
  ClipboardList,
  CreditCard,
  History,
  LayoutDashboard,
  LifeBuoy,
  Map,
  PackagePlus,
  PackageSearch,
  Route,
  ScrollText,
  Settings,
  Store,
  Tag,
  Truck,
  UserCog,
  Users,
  Navigation,
} from 'lucide-react';

import type { LucideIcon } from 'lucide-react';
import type { NavIcon } from '@/lib/types';

export const NAV_ICONS: Record<NavIcon, LucideIcon> = {
  dashboard: LayoutDashboard,
  book: PackagePlus,
  deliveries: ClipboardList,
  track: PackageSearch,
  merchant: Store,
  payments: CreditCard,
  notifications: Bell,
  profile: CircleUserRound,
  support: LifeBuoy,
  current: Navigation,
  history: History,
  cod: Banknote,
  shipments: Truck,
  bulk: Boxes,
  bulkShipments: FileSpreadsheet,
  dispatch: Route,
  drivers: Users,
  customers: Users,
  map: Map,
  activity: ScrollText,
  operators: UserCog,
  business: Briefcase,
  merchants: Building2,
  pricing: Tag,
  reports: BarChart3,
  settings: Settings,
};
